"""VTube Studio 控制器使用的默认 Live2D 参数名。"""

BLINK_LEFT_PARAMETER = "EyeOpenLeft"
BLINK_RIGHT_PARAMETER = "EyeOpenRight"
BODY_SWING_X_PARAMETER = "FaceAngleX"
BODY_SWING_Z_PARAMETER = "FaceAngleZ"
BREATHING_PARAMETER = "FaceAngleY"
EYE_LEFT_X_PARAMETER = "EyeLeftX"
EYE_LEFT_Y_PARAMETER = "EyeLeftY"
EYE_RIGHT_X_PARAMETER = "EyeRightX"
EYE_RIGHT_Y_PARAMETER = "EyeRightY"
MOUTH_SMILE_PARAMETER = "MouthSmile"
MOUTH_OPEN_PARAMETER = "MouthOpen"
IDLE_PRIORITY = 10
